name: Test, build and push npm package
on:
  workflow_dispatch:
  push:

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Environment
        run: |
          npm version
          env

      - uses: actions/checkout@v2

      - name: Build npm package
        run: |
          pushd packages/covid-certificate-parser
          npm install
          npm run build
          popd

      - name: Test npm package
        run: |
          pushd packages/covid-certificate-parser
          npm run lint
          npm run test
          popd

      - uses: JS-DevTools/npm-publish@v1
        id: npm-publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/covid-certificate-parser/package.json

      - name: NPM publish confirmation
        if: steps.npm-publish.outputs.type != 'none'
        run: |
          echo "NPM package version changed: ${{steps.npm-publish.outputs.old-version}} => ${{steps.npm-publish.outputs.version}}"
          echo "NPM package published to ${{steps.npm-publish.outputs.tag}}"
