name: Build and deploy Angular webapp
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build npm package
        run: |
          pushd packages/covid-certificate-parser
          npm install
          npm run build
          popd

      - name: Build and deploy Angular webapp
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: /covid-certificate-scanner/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/covid-certificate-scanner
