name: Test, build and push npm package
on:
  workflow_dispatch:
  push:

jobs:
  npm:
    runs-on: ubuntu-latest
    env:
      PUSH: false #${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Environment
        run: |
          npm version
          env

      - uses: actions/checkout@v2

      - name: Build npm package
        run: |
          pushd packages/covid-certificate-parser
          npm install
          npm run build
          popd

      - name: Test npm package
        run: |
          pushd packages/covid-certificate-parser
          npm run lint
          npm run test
          popd

      - uses: JS-DevTools/npm-publish@v1
        if: ${{ env.PUSH == 'true' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/covid-certificate-parser/package.json
          #todo: will not be triggered
