name: Test, build and push npm package
on:
  workflow_dispatch:
  push:

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Environment
        run: |
          npm version
          env

      - uses: actions/checkout@v2

      - name: Build npm package
        working-directory: packages/covid-certificate-parser
        run: |
          npm install
          npm run build

      - name: Test npm package
        working-directory: packages/covid-certificate-parser
        run: |
          npm run lint
          npm run test

      - name: Publish npm package
        working-directory: packages/covid-certificate-parser
        run: |
          npm install -g @jsdevtools/npm-publish
          npm-publish --token=${{ secrets.NPM_TOKEN }}
